### ISSUE TITLE
Dynamic items are not rendered 

### ISSUE THREAD

**Issue by abhijitgujar86** [rsdavis/svelte-collapsible#1]
when Loading dynmic data via aray like below the accordion stays expanded and non responsive to clicks 

`
       
            <Accordion  bind:active_accord >

              {#each nav_menu as { key, body }, i}

                       {#key active_accord}

                        <AccordionItem key='{key}'>{@html body}</AccordionItem>
                        {/key}
              {/each}
         </Accordion>
`

**Comment by rsdavis** [comment]
I am not sure exactly what you are trying to achieve, but it works for me using an array of items. 
As shown in the readme, the AccordionItem component has two slots, "header" and "body". 
You need to use those in order for the item to work.
Here is an example that I think does what you want.

```
<Accordion>
	{#each nav_menu as { key, body }, i}
		{#key key}
			<AccordionItem key='{key}'>
				<div slot='header'>{key}</div>
				<div slot='body'>{@html body}</div>
			</AccordionItem>
		{/key}
	{/each}
</Accordion>
```
