### ISSUE TITLE
TypeScript compatibility

### ISSUE THREAD

**Issue by st--** [rsdavis/svelte-collapsible#2]
I'm using this component in a TypeScript-based app. When running `npx svelte-check`, I get the following TypeScript compiler error:
```
src/App.svelte:26:35
Error: Cannot find module 'svelte-collapsible' or its corresponding type declarations. (ts)
  import { CollapsibleCard } from "svelte-collapsible";
```
I believe this could be fixed by exporting types. My initial search regarding what changes would be required came up with https://github.com/sveltejs/component-template/issues/29 and this linked typed template: https://github.com/mattjennings/svelte-typescript-component-template (which ensures it can be consumed by both typescript and plain javascript apps) - would you be willing to make the corresponding changes to your component package?

**Comment by rsdavis** [comment]
I have never used TypeScript so I'm not familiar with it. But I will accept a PR :)

**Comment by Alfagun74** [comment]
just declare a module in your types folder

svelte-collapsible.d.ts
```ts
declare module "svelte-collapsible";
```
