### ISSUE TITLE
Custom elements

### ISSUE THREAD

**Issue by nfq** [rsdavis/svelte-collapsible#3]
Is it possible to use custom elements rather than the default divs? For instance, I'd like the AccordionItem to be a UL and the body to be an LI for instance?

**Comment by rsdavis** [comment]
@nfq This is a good suggestion, I agree that the components should use semantic html ... I will make these modifications this weekend.

**Comment by rsdavis** [comment]
I changed the accordion components to use `ul` and `li` and updated the package version to `0.2.1`.

**Comment by nfq** [comment]
Great, thank you.
What would be ideal, would be if you could choose which elements are the body and AccordionItem.
For instance, if one chose to use the HTML5 details and summary. I'd use this if I could btw, but it's almost impossible to animate/transition reliably.

Thoughts?

**Comment by rsdavis** [comment]
I'm not sure exactly what you mean. Even if it's possible to allow the user to choose which elements they want to use, I'm not sure that would be desirable. 

However, looking at the HTML documentation for `<details>` and `<summary>`, they do seem appropriate for this use case. I could modify the accordion item html to look like the following ...

```html
<li class='accordion-item' aria-expanded={params.open}>

    <summary class='accordion-item-header' on:click={handleToggle}>
        <slot name='header' />
    </summary>

    <details class='accordion-item-body' use:collapse={params}>
        <slot name='body' />
    </details>

    <slot/>

</li>
```

And, if I am making these changes, I might as well rename "header" and "body" to "summary" and "details".

What do you think?

**Comment by nfq** [comment]
Yeah, I agree. And good point: with `summary` and `details`, one wouldn't need custom elements.
One question: is the outer element then always an `li`? If yes, that forces the dev to always remember to wrap it in a `ul`. Wonder if a `div` is then better.
