### ISSUE TITLE
open/close all cards

### ISSUE THREAD

**Issue by liam-k** [rsdavis/svelte-collapsible#4]
Hi, thank you for making this! Is there a possibility to open or close all CollapsibleCard elements on a page? It doesn’t seem to be possible by setting the Accordions key variable (which makes sense since that’s how an accordion works, I guess...), but is there a way to access the state of the simple card elements? I’d like to have a "toggle all open" button or something like that, and set the default state for all cards in the code.

**Comment by rsdavis** [comment]
Hi @liam-k , you can accomplish this by binding the open state of the cards and controlling it yourself. I created this demo as an example https://svelte.dev/repl/4d6dc6aa86a6486d9c85d8066eb46d80?version=3.44.0

If you like `svelte-collapsible` please consider starring :star:

**Comment by liam-k** [comment]
Thank you for the demo! Unfortunately that’s what I had already tried, and the problem with this method is that clicking one of the cards to open it also opens all the cards. What I’m looking for is the possibility to open and close all cards via button, but still have the ability to open and close individual cards without affecting the others. 

Sorry if that was unclear, I should’ve written into the issue what I already tried...

**Comment by rsdavis** [comment]
Ok, I have just updated the demo to achieve what you want. Since each card needs to be controlled individually, you will need to maintain the open state for each one separately. Then opening/closing all of them just means changing all of their state.

**Comment by liam-k** [comment]
Ah, now I see how it works. Thank you so much for your time and quick replies, you’ve really helped me out!!
