### ISSUE TITLE
How bind accordion open

### ISSUE THREAD

**Issue by matheuslemke** [rsdavis/svelte-collapsible#7]
Using `CollapsibleCard` is possible to bind open property using `bind:open`, like:
```svelte
{ #each cards as card }
    <CollapsibleCard bind:open={card.open}>
        <h2 slot='header' class='header'>{ card.header }</h2>
        <p slot='body' class='body'>{ card.body }</p>
    </CollapsibleCard>
{ /each }
```

With `Accordion` and `AccordionItem` it is not possible.

Do you guys think that it's a problem to export the `open` property of `AccordionItem`? Or is there a different way of doing this?

**Comment by rsdavis** [comment]
I'm not sure exactly what you are trying to achieve.
Try binding the key on the Accordion, it will be null when the accordion is closed.

```
<script>
  let key
  $: open = key !== null
</script>
<Accordion bind:key>
</Accordion>
```

**Comment by samal-rasmussen** [comment]
You may trigger opening/closing of AccordionItems by setting the key to what you want:
```
<script>
  const items = [
    {  key: 'a',
...
  let key;
</script>
<button on:click={() => key = 'a'}>Open A</button>
<button on:click={() => key = 'b'}>Open B</button>
<button on:click={() => key = 'c'}>Open C</button>

<Accordion bind:key>
  { #each items as item }
    <AccordionItem key={item.key}>
...
```

Example repl:
https://svelte.dev/repl/45a67bf54d4e4d988fd5d33a7e4a60e1?version=4.2.2

**Comment by matheuslemke** [comment]
The correct way is binding the `key` prop and not the `open`.
